package telas;

import floreve.clienteDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author ander
 */
public class newCliente extends javax.swing.JFrame {
    clienteDAO cli;
    /**
     * Creates new form newCliente
     */
    public newCliente() {
        initComponents();
        initcustom();
    }

    private void initcustom(){
        cli = new clienteDAO();
        setTitle("adicionar Clientes");
        setResizable(false);
        
        if(!cli.banco.GetConnection()){
          JOptionPane.showMessageDialog(null, "Falha na conexão");
          System.exit(0);
        }
    }
    
    void limpaCampos(){
        tf_EnderecoCliente.setText("");
        tf_NomeCliente.setText("");
        tf_TelefoneCliente.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_adicionar = new javax.swing.JButton();
        bt_Cancelar = new javax.swing.JButton();
        tf_EnderecoCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_TelefoneCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_NomeCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt_adicionar.setText("Adicionar");
        bt_adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_adicionarActionPerformed(evt);
            }
        });

        bt_Cancelar.setText("Cancelar");
        bt_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CancelarActionPerformed(evt);
            }
        });

        tf_EnderecoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_EnderecoClienteActionPerformed(evt);
            }
        });

        jLabel4.setText("Endereço:");

        tf_TelefoneCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_TelefoneClienteActionPerformed(evt);
            }
        });

        jLabel3.setText("telefone:");

        tf_NomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_NomeClienteActionPerformed(evt);
            }
        });

        jLabel2.setText("nome:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_EnderecoCliente)
                    .addComponent(tf_TelefoneCliente)
                    .addComponent(tf_NomeCliente)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_adicionar, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_Cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(tf_NomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_TelefoneCliente)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(tf_EnderecoCliente, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_adicionar, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(bt_Cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_adicionarActionPerformed

        if(tf_NomeCliente.getText().equals("")){
            JOptionPane.showMessageDialog(null, "campo nome vazio!");
            tf_NomeCliente.requestFocus();
            return;
        }
        if(tf_EnderecoCliente.getText().equals("")){
            JOptionPane.showMessageDialog(null, "campo endereço vazio!");
            tf_EnderecoCliente.requestFocus();
            return;
        }
        if(tf_TelefoneCliente.getText().equals("")){
            JOptionPane.showMessageDialog(null, "campo do telefone vazio!");
            tf_TelefoneCliente.requestFocus();
            return;
        }
        
        cli.c1.setEndereco(tf_EnderecoCliente.getText());
        cli.c1.setNome(tf_NomeCliente.getText());
        cli.c1.setTelefone(tf_TelefoneCliente.getText());
        JOptionPane.showMessageDialog(null, cli.atualizar(clienteDAO.INCLUSAO));
        limpaCampos();
    }//GEN-LAST:event_bt_adicionarActionPerformed

    private void bt_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CancelarActionPerformed
        dispose();
    }//GEN-LAST:event_bt_CancelarActionPerformed

    private void tf_EnderecoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_EnderecoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_EnderecoClienteActionPerformed

    private void tf_TelefoneClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_TelefoneClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_TelefoneClienteActionPerformed

    private void tf_NomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_NomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_NomeClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Cancelar;
    private javax.swing.JButton bt_adicionar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tf_EnderecoCliente;
    private javax.swing.JTextField tf_NomeCliente;
    private javax.swing.JTextField tf_TelefoneCliente;
    // End of variables declaration//GEN-END:variables
}
