package telas;

import floreve.fornecimentoPlantaDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author ander
 */
public class newFornPlanta extends javax.swing.JFrame {
    fornecimentoPlantaDAO fpl;
    /**
     * Creates new form newFornPlanta
     */
    public newFornPlanta() {
        initComponents();
        initcustom();
    }

    private void initcustom(){
        fpl = new fornecimentoPlantaDAO();
        setTitle("novo Fornecimento (Plantas)");
        setResizable(false);
        
    if(!fpl.banco.GetConnection()){
        JOptionPane.showMessageDialog(null, "Falha na conexão");
        System.exit(0);    
        }     
    }
        
    void limpaCampos() {
            tf_idFornecedor.setText("");
            tf_idPlanta.setText("");
            tf_Dia.setText("");
            tf_Mes.setText("");
            tf_Ano.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_cancelar = new javax.swing.JButton();
        bt_adicionar = new javax.swing.JButton();
        tf_idPlanta = new javax.swing.JTextField();
        tf_idFornecedor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_Dia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_Mes = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_Ano = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt_cancelar.setText("Cancelar");
        bt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarActionPerformed(evt);
            }
        });

        bt_adicionar.setText("Adicionar");
        bt_adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_adicionarActionPerformed(evt);
            }
        });

        tf_idPlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_idPlantaActionPerformed(evt);
            }
        });

        tf_idFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_idFornecedorActionPerformed(evt);
            }
        });

        jLabel2.setText("ID do fornecedor:");

        jLabel3.setText("ID da planta:");

        tf_Dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_DiaActionPerformed(evt);
            }
        });

        jLabel4.setText("Dia:");

        jLabel5.setText("mês:");

        tf_Mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_MesActionPerformed(evt);
            }
        });

        jLabel6.setText("Ano:");

        tf_Ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_AnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_idFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(tf_idPlanta)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(bt_adicionar)
                        .addGap(18, 18, 18)
                        .addComponent(bt_cancelar)))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(tf_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(tf_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel6)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(tf_Ano, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(41, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tf_idFornecedor)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tf_idPlanta)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(71, 71, 71)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tf_Ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addGap(71, 71, 71)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_bt_cancelarActionPerformed

    private void bt_adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_adicionarActionPerformed
        if(tf_idPlanta.getText().equals("")){
            JOptionPane.showMessageDialog(null, "campo id da planta vazio!");
            tf_idPlanta.requestFocus();
            return;
        }

        if(tf_idFornecedor.getText().equals("")){
            JOptionPane.showMessageDialog(null, "campo id do fornecedor vazio!");
            tf_idFornecedor.requestFocus();
            return;
        }

        if(tf_Dia.getText().equals("")){
            JOptionPane.showMessageDialog(null, "campo Dia vazio!");
            tf_Dia.requestFocus();
            return;
        }
        if(tf_Mes.getText().equals("")){
            JOptionPane.showMessageDialog(null, "campo Mes vazio!");
            tf_Mes.requestFocus();
            return;
        }
        if(tf_Ano.getText().equals("")){
            JOptionPane.showMessageDialog(null, "campo Ano vazio!");
            tf_Ano.requestFocus();
            return;
        }
        String dataForn = (tf_Ano.getText()+"-"+tf_Mes.getText()+"-"+tf_Dia.getText());
        fpl.f1.setIdFornecedor(Integer.parseInt(tf_idFornecedor.getText()));
        fpl.f1.setIdPlanta(Integer.parseInt(tf_idPlanta.getText()));
        fpl.f1.setData(dataForn);
        JOptionPane.showMessageDialog(null, fpl.atualizar(fornecimentoPlantaDAO.INCLUSAO));
        limpaCampos();
    }//GEN-LAST:event_bt_adicionarActionPerformed

    private void tf_idPlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_idPlantaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_idPlantaActionPerformed

    private void tf_idFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_idFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_idFornecedorActionPerformed

    private void tf_DiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_DiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_DiaActionPerformed

    private void tf_MesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_MesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_MesActionPerformed

    private void tf_AnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_AnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_AnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newFornPlanta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newFornPlanta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newFornPlanta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newFornPlanta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newFornPlanta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_adicionar;
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField tf_Ano;
    private javax.swing.JTextField tf_Dia;
    private javax.swing.JTextField tf_Mes;
    private javax.swing.JTextField tf_idFornecedor;
    private javax.swing.JTextField tf_idPlanta;
    // End of variables declaration//GEN-END:variables
}
